"""Verification: read dimensions back from the written files and compare to the spec.

- DXF: every DIMENSION entity is looked up by handle and its measurement read
  from the saved file (real mm, model space at 1:1).
- SVG: the internal shell outline (gid SHELL) is measured in points and
  converted to real mm at 1:20.
- PDF: the page size is read from the MediaBox and checked against A3.
- Cross-check: shared dimensions must agree between plans and elevations.
"""

import re
from pathlib import Path

import ezdxf

from build import OUT, SCALE, W, D, CEIL, SHELF, DOOR_W, CTR, PROPOSED_TBC

PT = 72 / 25.4
TOL = 0.5  # mm


def svg_shell(path):
    s = path.read_text()
    m = re.search(r'<g id="SHELL">\s*<path d="([^"]+)"', s)
    nums = [float(v) for v in re.findall(r"-?\d+\.?\d*", m.group(1))]
    xs, ys = nums[0::2], nums[1::2]
    return ((max(xs) - min(xs)) / PT * SCALE, (max(ys) - min(ys)) / PT * SCALE)


def pdf_page(path):
    b = path.read_bytes()
    m = re.search(rb"/MediaBox\s*\[\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)", b)
    return float(m.group(3)) / PT, float(m.group(4)) / PT


def run(built):
    rows, tbc_rows, xcheck = [], [], {}
    shells = {"SD-01": (W, D), "SD-02": (W, D), "SD-03": (W, D), "SD-04": (W, D),
              "SD-05": (W, CEIL), "SD-06": (W, CEIL), "SD-07": (D, CEIL), "SD-08": (D, CEIL)}
    fails = 0
    for stem, sheet in built:
        no = sheet.no
        doc = ezdxf.readfile(OUT / f"{stem}.dxf")
        for d in sheet.dims:
            if d.get("ratio"):
                val, src = d["paper"], "geometry"
                val = round(val, 3)
            elif d.get("bar"):
                val, src = d["paper"] * SCALE, "sheet"
            elif d["handle"]:
                ent = doc.entitydb[d["handle"]]
                val, src = round(ent.get_measurement(), 1), "DXF"
            else:
                val, src = round(d["paper"] * SCALE, 1), "computed"
            exp = d["expect"]
            if exp is None:
                tbc_rows.append((no, d["key"], val, d["text"]))
                continue
            tol = 0.01 if d.get("ratio") else TOL
            ok = abs(val - exp) <= tol
            fails += not ok
            rows.append((no, d["key"], f"{val:g}", src, f"{exp:g}", "YES" if ok else "NO"))
            xcheck.setdefault(d["key"], []).append((no, val))
        sw, sh = svg_shell(OUT / f"{stem}.svg")
        ew, eh = shells[no]
        for k, v, e in (("shell width (SVG)", sw, ew), ("shell height (SVG)", sh, eh)):
            ok = abs(v - e) <= 1.0
            fails += not ok
            rows.append((no, k, f"{v:.1f}", "SVG", f"{e:g}", "YES" if ok else "NO"))
        pw, ph = pdf_page(OUT / f"{stem}.pdf")
        ok = abs(pw - 420) < 0.5 and abs(ph - 297) < 0.5
        fails += not ok
        rows.append((no, "page size (PDF)", f"{pw:.1f}x{ph:.1f}", "PDF", "420x297",
                     "YES" if ok else "NO"))

    # plan vs elevation cross-checks
    def vals(key):
        return xcheck.get(key, [])

    pairs = [
        ("internal width plans = elevation length SD-06",
         [v for _, v in vals("internal width")] + [v for n, v in vals("elevation length")
                                                   if n == "SD-06"], W),
        ("internal depth plans = elevation length SD-07/08",
         [v for _, v in vals("internal depth")] + [v for n, v in vals("elevation length")
                                                   if n in ("SD-07", "SD-08")], D),
        ("shopfront width SD-05 = plan width", [v for _, v in vals("shopfront internal width")], W),
        ("ceiling height all elevations",
         [v for _, v in vals("floor to ceiling")] + [v for _, v in vals("floor to ceiling (ref)")],
         CEIL),
        ("unit depth plan = rear elevation section",
         [v for k in ("side unit depth L", "side unit depth R", "unit depth L", "unit depth R")
          for _, v in vals(k)], SHELF),
        ("door width SD-05 = spec", [v for _, v in vals("door leaf width")], DOOR_W),
        ("counter width SD-02 = SD-06", [v for _, v in vals("counter width")], CTR["W"]),
    ]
    xrows = []
    for name, vs, exp in pairs:
        ok = bool(vs) and all(abs(v - exp) <= TOL for v in vs)
        fails += not ok
        xrows.append((name, len(vs), ", ".join(sorted({f"{v:g}" for v in vs})), f"{exp:g}",
                      "YES" if ok else "NO"))

    md = ["# Verification - drawings/claude", "",
          "Generated by `src/verify.py` after every build. Values are read back from the",
          "written files: DXF dimension entities (real mm), the SVG shell outline (points",
          "converted at 1:20) and the PDF MediaBox.", "",
          f"**Result: {'ALL PASS' if fails == 0 else f'{fails} FAIL(S)'}**", "",
          "## Dimension check", "",
          "| Drawing | Dimension | File value | Read from | Spec value | Match |",
          "|---|---|---|---|---|---|"]
    md += [f"| {' | '.join(r)} |" for r in rows]
    md += ["", "## Plan vs elevation cross-check", "",
           "| Check | Instances | Values found | Spec | Match |", "|---|---|---|---|---|"]
    md += [f"| {r[0]} | {r[1]} | {r[2]} | {r[3]} | {r[4]} |" for r in xrows]
    md += ["", "## Dimensions shown as TBC (not checked against the spec)", "",
           "| Drawing | Dimension | Drawn length (placeholder) | Label |", "|---|---|---|---|"]
    md += [f"| {a} | {b} | {c:g} | {d} |" for a, b, c, d in tbc_rows]
    md += ["", "## Proposed TBC items (not yet in spec/TBC.md)", ""]
    md += [f"- **#{k}** {v}" for k, v in PROPOSED_TBC.items()]
    (OUT / "VERIFICATION.md").write_text("\n".join(md) + "\n")
    print("\n".join(md))
    if fails:
        raise SystemExit(f"verification failed: {fails}")
